apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: repo-1410296180
  namespace: argocd
spec:
  encryptedData:
    project: AgAWJ7HYRMIBrzihI6LEBilolFQv6kFUkDuHJUxENdKBnSIbBdpmUtgW1wakSl2l3qoQGarYTUQCgA8F558Ihre0/uvbdXNUP3quQ7hG3jYRijrqlMO6ByO+Y1rnV+GnXEMesj5SwSE5ORA782N3RNmtbnSsk9y7scgeKi/ROzLS5Wd3eI+k5FDfj6sRC2rCTCGVa1ypV0/YgQjQb9gLJTykO5G1R2VmsISHowEM7woXWbKeQrhY+W5JAkiF6DPPaAECgCljvD79z9hjelTFML+2GwOcteEFs1AJ8O4fH3Y+inR1Pq+aZsqSZDAH5/MCMUYuU/MWZgdB54CnTItSVx+ZCAdC9LPVoM0pYm1X/v/8kLIiI+d6Co6oyAeyFM/kvr/c6EoNvN8O4zvrF0TOe9GC8kNgOK/iBh6f7KwJRvML3LNqJ7Vnpgx6wISPod9Px3P9+V9JCjqUBH/mt9Tl3dH6hF+kiGuhGIPaHlR5TXh7i+wHT+ll2X1AlV3rXt0dfaDfSc8gcBdHlrP2LCd1bElet2fZrS3uT9ssHLRmioBnFaaP2faATIt9hWRnXWzpTbpn7EVJa5268FizYfJjaLlIct21LGsNZn4ldNqPLH3EDEsHW6dADwd8XXwyJNDWprjn94Hg5iXrbq59IeSfnplJyIAlXonhhU/K01dlwmYnGtjSSGWiHe+iMxK+YX+AuaBpmKAbTUaE
    type: AgB9tR+D0dK75EWhZxIE7wat/81bw8/F5fy8yZwzj/dEVotux38eWTIKKsovs0k2Ia089Xjg13OTLZzoSutzeLW0Rnr7tqffd0uByRZBrzgQAd0qF9BeXdNfonSA9hZum9/dctJDgq7O0fsEwDUEw56SPySyooy2OqLWanple3VmqolM4Et+1Rc2EZHrlM1O/pQBvCxSIxRx1JJvSNUAQcOgoAtvh6EFh6lSth3WWBRTI19Xw3kJMXnGjc3gWfF/FExz00t53SmtEti1RS2whB5obcB9DHTG5PlJC8VL+iP2gVQsuCstqmZysOw42+u+/1mGMCqEosmaVspLqOokgf7ruAiKrL/a4jMMn1ljARN096uE/CV4zp4HlaPYBBKcZAEyVNWzlS/FMOhFhTg9TOVJJkWDPif9FjR/cg1EbHpCPSZ2Vdq4ucm5XXHhLLjO7P2h7P4gDutOGwn17TV9dxYmLKWuV17kTrnc4nqFw8fattCriD9VSeHjjL7hiR4mzbXZ37LbfPp7VVqBGYnuGX/TFlIhJ0rMgyWa9HMA1zE4Ix/kuKeLtEwBihwIJK7+pClRswJnOy+1Z2NDWSuH6MUtNVh5AkLgnLEUrny+fEm+zQcj0bZ+Mz3LrUOUotRnraNGbwgj8oEAQpWAV7Mx86J/YHni9HHC0aS8Pp1qQLLa8DOlnherX57nMpHzCAIi1rcjGRg=
    url: AgBT36UQOANNiB/Ki1LcXY5vK2EVm0aFkdgH9ILAzIvNRg01pX8Cd0hycJWIUW2Y0pgPe6DJqTo5Lhemh5KeAXeAKrK+VjGLJZIlKkuFM+MYNnvHtOe2HXaNf6IJuaukdh2HRBvLLVkQ1XqqG8f7AQs11/9nTf8qw8RsB7/WF1/b7cnnxGpP54M9FiXiMr80/f8n0JNilC3y7OH6GMDgpWIrvQ0Tqa9BLkNeuEBT/GX8nLtt1ZkaFKwpmlcRftChYEp/V6fE8tSCM2PUxiSl/tBzVaGuKIFgfLnBLjr8cBfoau0NPTBjss+gqzP9epvSc2iko5i5bvvrIy44vWdSsiwxTwjuYvtJRUzYzQzKdw56atG3J6ZDbUKpfzNkhpB34vritfJcnyBcW8ue4xTBiQJb/EuzCYxx8P3XTeEUwb3WKhNNekyzC+JTXcciy5sgUPOMf6+sd2lyivKSCjuARLrTDkkROeenMFO7VbWTt+A6JYjrWVEQ0v+wAIFTj21bFsgqc1yh46RHN7OvVsHYwQWHsVstaLwmRov73XmEzFVutJ5nbI0sIzzPc0A9rqXi0b7V2d9RWhjQUosepSD/3c9/ziV0lk3bXEcChJOr+5onC1OzHdTC0EwL6YqxV9JB8ZL08k4KhENnGtwUHX9/CNTLfV3NSpYvLCnuUy3c8wVIogqo7cFTpuXZo7K9FySBRE0ftTG3mBjU+TXDQvTVQ9mIjBtijFgXcpA1MzvO+xEdhcheI+2vCJFgNS0+VeU7OQ4/qOeytg==
  template:
    metadata:
      annotations:
        managed-by: argocd.argoproj.io
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: repo-1410296180
      namespace: argocd
    type: Opaque

